[package]
name = "offreg"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-result = "0.2.0"
windows-sys = { version = "0.59.0", features = ["Wdk_System_OfflineRegistry", "Win32_Security", "Win32_Foundation"] }
